demo run with success.

log:

#!/bin/bash
source /home/amd_clmc/team/workspace/devel/setup.bash
cd /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_python/demos/
chmod +x ci_example_ros_demo
./ci_example_ros_demo /home/amd_clmc/team/workspace/devel


------ setting parameters -----

------ PYTHON DEMO START ------

pid using ros parameter server
reading ros parameters: kp, kd, ki
PID controller: kp:1 kd:1 ki:1
force: -1.101
WARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.

------ DEMO END ------

[31mload_parameters: unable to set parameters (last param was [/rosdistro=groovy
]): [Errno 111] Connection refused[0m
Traceback (most recent call last):
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/__init__.py", line 279, in main
    p.start()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self.runner.launch()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/launch.py", line 644, in launch
    self._setup()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/launch.py", line 631, in _setup
    self._load_parameters()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/launch.py", line 328, in _load_parameters
    r  = param_server_multi()
  File "/usr/lib/python2.7/xmlrpclib.py", line 998, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 962, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 822, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 784, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 765, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
... logging to /root/.ros/log/5beb3c00-4649-11e6-a037-0242ac110003/roslaunch-amd-clmc-12-04-ci-4653.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
]2;roscore
[1mstarted roslaunch server http://amd-clmc-12-04-ci:57510/[0m
ros_comm version 1.9.55


SUMMARY
========

PARAMETERS
 * /rosdistro
 * /rosversion

NODES

auto-starting new master
[1mprocess[master]: started with pid [4667][0m
[1mROS_MASTER_URI=http://amd-clmc-12-04-ci:11311/[0m
]2;roscore http://amd-clmc-12-04-ci:11311/
[1msetting /run_id to 5beb3c00-4649-11e6-a037-0242ac110003[0m
[rosout-1] killing on exit
[1mprocess[rosout-1]: started with pid [4710][0m
started core service [/rosout]
[master] killing on exit
